name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  http: ^0.13.1
  meta: ^1.3.0
  csv: ^5.0.0
  recase: ^4.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0 
  source_gen: ^1.0.0
  build: ^2.0.0
  analyzer: ^5.12.0
  collection: ^1.15.0
  intl: ^0.18.0

  # flutter_sheet_localization: ^5.1.1
  flutter_sheet_localization:
    git:
      url: https://github.com/nguyenlamzx/flutter_sheet_localization
      path: flutter_sheet_localization
      ref: 4c5c20a456ab17e97f6d19cc1ec0602f0fb0ced8
  # flutter_sheet_localization:
  #   path: ../flutter_sheet_localization

  # localization_builder: ^0.15.7
  localization_builder:
    git:
      url: https://github.com/nguyenlamzx/flutter_sheet_localization
      path: localization_builder
      ref: 4c5c20a456ab17e97f6d19cc1ec0602f0fb0ced8
  # localization_builder:
  #   path: ../localization_builder

# dependency_overrides:
#   analyzer: '>=4.4.0 <6.0.0'
#   build: ">=2.1.0 <2.4.0"
#   build_config: ">=1.1.0 <1.2.0"
#   build_daemon: ^3.1.0
#   build_resolvers: 2.2.0
#   build_runner_core: ^7.2.0
#   code_builder: ^4.2.0
#   collection: ^1.15.0
#   crypto: ^3.0.0
#   dart_style: 2.2.4
#   source_gen: 1.2.7
#   file: 6.1.4

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^2.0.2

  flutter_lints: ^2.0.0
