name: localization_builder
description: A data class builder for localization.
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
version: 0.15.7

publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter 
  recase: ^4.0.0
  yaml: ^3.1.0
  equatable: ^2.0.0
  collection: ^1.15.0
  dart_style: ^2.0.0
  logging: ^1.0.0

  # template_string: ^0.6.0
  template_string:
    git:
      url: https://github.com/nguyenlamzx/flutter_sheet_localization
      path: template_string
      ref: 4c5c20a456ab17e97f6d19cc1ec0602f0fb0ced8
  # template_string:
  #   path: ../template_string

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.0

  flutter_test:
    sdk: flutter
