name: example
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter 
  logging: ^1.0.0
  http: ^0.13.0
  csv:
  # template_string:
  template_string:
    path: ../../template_string
  localization_builder: 
    path: ../